---
- name: Pre command for nested image
  command: "{{ item.pre_cmd }}"
  args:
    chdir: "{{ bootmedia_tmp_dir }}"
    warn: false
  become: true
  when: item.pre_cmd is defined

- name: "Copy template {{ item.src }} to {{ item.dest }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true

- name: Post command for nested image
  command: "{{ item.post_cmd }}"
  args:
    chdir: "{{ bootmedia_tmp_dir }}"
  become: true
  when: item.post_cmd is defined
