- name: Create directory structure for shipped tarfiles
  file: 
    state: directory
    path: "{{ bootmedia_custom_tarball.src }}/{{ item.dest }}" 
  loop:
    "{{ bootmedia_custom_tarball.directories }}"

- name: Append files that should be shipped with BootISO and deployed on target system
  copy: 
    remote_src: "{{ item.remote_src }}"
    src: "{{ item.src }}" 
    dest: "{{ bootmedia_custom_tarball.src }}/{{ item.dest }}"
  loop:
    "{{ bootmedia_custom_tarball.files }}"

- name: Create tarball of appended files and ship on the BootISO
  command: "tar cf {{ bootmedia_tmp_dir }}/{{ bootmedia_custom_tarball.dest }} ."
  args:
    chdir: "{{ bootmedia_custom_tarball.src }}"
    warn: false
