- name: Load a variable file based on the OS distribution
  include_vars: "vars/distribution/{{ bootmedia_data.distribution.lower() }}.yml"

- name: Load variable file based on the bootmedia_target system
  include_vars: "vars/system/{{ bootmedia_target_system }}.yml"

- name: Load variable file based on the bootmedia_target system family
  include_vars: "vars/system-family/{{ bootmedia_target_system_family }}.yml"
