---
  # register bootmedia_host as fact that can be used by handlers
- name: Register bootmedia_host as fact
  set_fact: 
    bootmedia_host: "{{ bootmedia_host }}"

- name: Load system and os specific vars 
  import_tasks: bootmedia_vars.yml
  delegate_to: "{{ bootmedia_host }}"

- name: Perform required pre-tasks to create bootmedias
  import_tasks: bootmedia_init.yml
  delegate_to: "{{ bootmedia_host }}"
  when: bootmedia_host_init_enabled

- name: Set selinux specific config for bootmedia usage
  import_tasks: bootmedia_selinux.yml
  delegate_to: "{{ bootmedia_host }}"
  when: bootmedia_host_selinux_config_enabled

- name: Perform tasks to create bootmedia
  import_tasks: bootmedia_prepare.yml
  delegate_to: "{{ bootmedia_host }}"
