---
- name: Load system and os specific vars 
  import_tasks: bootmedia_vars.yml

- name: Perform required pre-steps to create bootmedias
  include_tasks: 
    file: bootmedia_init.yml
    apply:
      delegate_to: "{{ host }}"
  loop:
      "{{ groups['bootmedia_host'] }}"
  loop_control:
    loop_var: host
  tags:
    - init

- name: Prepare bootmedia
  include_tasks: 
    file: bootmedia_prepare.yml
    apply:
      delegate_to: "{{ host }}"
  loop:
      "{{ groups['bootmedia_host'] }}"
  loop_control:
    loop_var: host

