---
  # according to this explanation [1]
  # we should use include_tasks
  # and a dedicated loop task file
  # that uses import_tasks
  # [1] https://medium.com/opsops/ansible-2-5-delegate-to-and-include-role-20cd7e67008e
- name: Loop with delegated bootmedia_hosts
  include_tasks: loop.yml
  loop:
      "{{ groups['bootmedia_host'] }}"
  loop_control:
    loop_var: bootmedia_host
